# This is a basic workflow to help you get started with Actions

name: Documentation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  doc:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install wheel setuptools cython
          python3 -m pip install pdoc3
          if [ -f requirements.txt ]; then python3 -m pip install -r requirements.txt; fi
        
        
      - name: Install package
        run: python3 -m pip install -e $GITHUB_WORKSPACE

      - name: Generator doc
        run: python3 -m pdoc --html rul_pm --force

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: html/rul_pm/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
